# Just these 3 to test locally
GITHUB_REPO=
GITHUB_TOKEN=
GITHUB_BRANCH=
GITHUB_DOCS_PATH=                   
MEILISEARCH_URL=

# Optional Neo4j / LLM for Graphiti
NEO4J_URI=
NEO4J_USER=
NEO4J_PASSWORD=
OPENAI_API_KEY=
OPENAI_MODEL=gpt-4o-mini
ANTHROPIC_API_KEY=
ANTHROPIC_MODEL=claude-3-5-sonnet-20240620
